image:
  repository: bitnami/kubectl
  tag: latest

compaction:
  # Settings for increasing compaction throughput
  increase:
    schedule: "0 1 * * *" # 8 PM EST in UTC
    throughput: 0 # Un-throttled compaction throughput

  # Settings for decreasing compaction throughput
  decrease:
    schedule: "0 5 * * *"  # 5 AM UTC, which is Midnight EST
    throughput: 256 # Decreased compaction throughput
  customJobs:
    espotpromos:
      schedule: "1 1 1,15 * *"  # 1:01 AM UTC on the 1st and 15th of each month
      command: "nodetool compact --split-output monetization espot_promos"
    promos:
      schedule: "1 1 7,21 * *"  # 1:01 AM UTC on the 7th and 21st of each month
      command: "nodetool compact --split-output monetization promos"

cassandra:
  namespace: cassandra
  label: statefulset.kubernetes.io/pod-name=monetization-cassandra
