{{- if .Values.configOverrides }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "cassandra.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cassandra.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $key, $value := .Values.configOverrides }}
  {{- if eq $key "jvm.options" }}
  jvm.options: |-
    {{- $.Files.Get "files/jvm.options" | nindent 8 }}
  {{- else }}
  {{ $key }}: |-
    {{- $value | nindent 8 }}
  {{- end }}
  {{- end }}
{{- end }}