apiVersion: batch/v1
kind: CronJob
metadata:
  name: increase-compaction-throughput
spec:
  schedule: "{{ .Values.compaction.increase.schedule }}"  # Uses schedule from values.yaml
  jobTemplate:
    spec:
      template:
        metadata:
          namespace: "{{ .Values.cassandra.namespace }}"
        spec:
          containers:
          - name: adjust-compaction
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: ["/bin/bash", "/scripts/adjust-compaction.sh", "0"]  # Un-throttled
            volumeMounts:
            - name: scripts
              mountPath: /scripts
          volumes:
          - name: scripts
            configMap:
              name: cassandra-scripts
          restartPolicy: OnFailure
