apiVersion: batch/v1
kind: CronJob
metadata:
  name: promos-compact-job
spec:
  schedule: "{{ .Values.compaction.customJobs.promos.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          namespace: "{{ .Values.cassandra.namespace }}"
        spec:
          containers:
          - name: promos-compact-job
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: ["/bin/bash", "-c", "{{ .Values.compaction.customJobs.promos.command }}"]
          restartPolicy: OnFailure
