{{- if .Values.gcsCredentials}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.gcsCredentials.secretName}}
  namespace: {{.Values.namespace}}
  annotations:
    harness.io/skip-versioning: "true"
data:
  bucket-credentials.json: {{.Values.gcsCredentials.secretValue}}
{{- end}}