apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{.Values.name}}
    app.kubernetes.io/instance: {{.Values.namespace}}
  name: {{.Values.name}}
  namespace: {{.Values.namespace}}
spec:
  type: {{.Values.serviceType}}
  ports:
    - port: {{.Values.servicePort}}
      targetPort: {{.Values.serviceTargetPort}}
      protocol: {{.Values.protocol}}
  selector:
    app.kubernetes.io/name: {{.Values.name}}
    app.kubernetes.io/instance: {{.Values.namespace}}