image:
  repository: bitnami/kubectl
  tag: latest

compaction:
  # Settings for increasing compaction throughput
  increase:
    schedule: "0 1 * * *" # 8 PM EST in UTC
    throughput: 0 # Un-throttled compaction throughput

  # Settings for decreasing compaction throughput
  decrease:
    schedule: "0 5 * * *"  # 5 AM UTC, which is Midnight EST
    throughput: 256 # Decreased compaction throughput
  customJobs:
    promos:
      schedule: "1 13 * * 1" # Every Monday at 8:01 EST
      command: "nodetool compact --split-output monetization promos"
    espotpromos:
      schedule: "1 13 * * 4" # Every Thursday at 8:01 EST
      command: "nodetool compact --split-output monetization espot_promos"

cassandra:
  namespace: cassandra
  label: statefulset.kubernetes.io/pod-name=monetization-cassandra
